version: '3.0'

services:
  main:
    container_name: main
    build: 
      context: .
    env_file: 
      - .env
    volumes:
      - .:/good-deeds-app
      - /good-deeds-app/node_modules
    ports:
      - 8000:8000
      - 9229:9229
    command: npm run start:dev
    depends_on: 
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
